version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: maornginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  drupal:
    image: drupal:latest
    container_name: maordrupal    
    restart: unless-stopped
    ports:
      - 80:80

  postgres:
    image: postgres:latest
    container_name: maorpostgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    


  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474    
     
    
